title: "Irontide: Daltrond"
baseurl: ""
url: "www.irontides.ga"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-autoprefixer

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: compressed